L.S.Home/Areas/admin/Controllers/SysDepController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;


namespace L.S.Home.Areas.admin.Controllers
{
    using L.S.Model.DatabaseModel.Context;
    using L.S.Model.DatabaseModel.Entity;
    using L.S.Interface;
    using L.S.Home.Models;
    using L.Study.Common;
    using Common;
    using Model.DomainModel.Sys;

    public class SysDepController : LsBaseController
    {
        public IDepService depService;

        public SysDepController(IDepService _depService)
        {
            depService = _depService;
        }

        [LSAuthorize("DepsManage", "SysManage", "DepsManage")]
        public ActionResult Index(int page = 1, int pageSize = 10)
        {
            var list = depService.GetPagedList(d => true, page, pageSize, modellist => modellist.OrderByDescending(d => d.AddDate));
            return View(list);
        }
        [LSAuthorize("DepsManage", "SysManage", "DepsManage")]
        public ActionResult TreeIndex(int page = 1, int pageSize = 10)
        {
            return View();
        }

        [LSAuthorize("DepsManage", "SysManage", "DepsManage")]
        public ActionResult GetSysDep(string id)
        {
            var model = depService.GetList(r => r.ID == id).Select(r => new SysDepViewModel
            {
                                 ID = r.ID,
                                 Name = r.Name,
                                 ParentID = r.ParentID,
                                 ParentName = r.Parent == null ? "" : r.Parent.Name,                                 
                                 IsAvailable = r.IsAvailable,
                                 AddBy = r.AddBy,
                                 AddDate = r.AddDate,                                 
                                 SortNo = r.SortNo,                                 
                             }).FirstOrDefault();            
            return Json(model, JsonRequestBehavior.AllowGet);
        }

        [LSAuthorize("DepCreate", "SysManage", "DepsManage")]
        public ActionResult Create()
        {
            return View();
        }


        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关详细信息，请参阅 http://go.microsoft.com/fwlink/?LinkId=317598。        
        [LSAuthorize("DepCreate", "SysManage", "DepsManage")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ParentID,IsAvailable,IsDel,Name,SortNo")] SysDep model)
        {            
            model.ID = IdentityCreator.NextIdentity;
            model.AddBy = cuser.UserID;
            model.AddByName = cuser.LoginName;
            model.AddDate = DateTime.Now;
            model.IsDel = false;
            if (string.IsNullOrEmpty(Request["SortNo"])) { model.SortNo = 0; }
            var parentDep=depService.Find(model.ParentID);
            if (parentDep != null)
            {
                model.ParentName = parentDep == null ? null : parentDep.Name;
                model.DepFullIDPath = parentDep.DepFullIDPath + model.ID + "/";
                model.DepFullNamePath = parentDep.DepFullNamePath  + model.Name + "/";
                depService.Add(model);
                if(depService.SaveChanges(out msg) > 0)
                {
                    return Json(new AjaxResult() { success = true, msg = insertSuccess, url = Url.Action("treeindex", "sysdep", "admin"), moremsg = msg });
                }
                else
                {
                    return Json(new AjaxResult() { success = false, msg = insertFailure, moremsg = msg });
                }
                
            }
            else
            {
                return Json(new AjaxResult() { success = false, msg = insertFailure, moremsg = "未找到上级组织" });
            }            
        }

        [LSAuthorize("DepEdit", "SysManage", "DepsManage")]
        public ActionResult Edit(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SysDep sysDep = depService.Find(id);
            if (sysDep == null)
            {
                return View("_NoDataInLayout");
            }
            return View(sysDep);
        }

        // POST: admin/sysdep/Edit/5
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 http://go.microsoft.com/fwlink/?LinkId=317598。
        [LSAuthorize("DepEdit", "SysManage", "DepsManage")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,AddBy,AddDate,ParentID,IsAvailable,Name,SortNo")] SysDep sysDep)
        {
            sysDep.UpdateBy = cuser.UserID;
            sysDep.UpdateByName = cuser.LoginName;
            sysDep.UpdateDate = DateTime.Now;
            sysDep.IsDel = false;
            if (string.IsNullOrEmpty(Request["SortNo"])) { sysDep.SortNo = 0; }
            var parentDep = depService.Find(sysDep.ParentID);
            if (parentDep != null||sysDep.ID=="root")//一般组织一定要有上级，顶级组织的ID为root，并且没有上级
            {
                sysDep.ParentName = parentDep == null ? null : parentDep.Name;
                sysDep.DepFullIDPath = parentDep == null ? "/"+sysDep.ID+ "/" : parentDep.DepFullIDPath  + sysDep.ID + "/";
                sysDep.DepFullNamePath = parentDep == null ? "/" + sysDep.Name + "/" : parentDep.DepFullNamePath + sysDep.Name + "/";
                depService.Update(sysDep);
                if (depService.SaveChanges(out msg) > 0)
                {
                    return Json(new AjaxResult() { success = true, msg = updateSuccess, url = Url.Action("treeindex", "sysdep", "admin"), moremsg = msg });
                }
                else
                {
                    return Json(new AjaxResult() { success = false, msg = updateFailure, moremsg = msg });
                }
            }
            else
            {
                return Json(new AjaxResult() { success = false, msg = updateFailure, moremsg = "未找到上级组织" });
            }            
        }

        [LSAuthorize("DepDelete", "SysManage", "DepsManage")]
        [HttpPost]
        public ActionResult Delete(string ids)
        {
            if (!string.IsNullOrEmpty(ids))
            {                
                if (depService.DepsDelete(ids, out msg) > 0)
                {
                    return Json(new AjaxResult() { success = true, msg = deleteSuccess, url = Url.Action("treeindex") });
                }
                else
                {
                    msg = errorOutPutToPage ? msg : deleteFailure;
                    return Json(new AjaxResult() { success = false, msg = msg });
                }
            }
            else
            {
                return Json(new AjaxResult() { success = false, msg = didnotchoosedata });
            }
        }
        [LSAuthorize("DepAvailable", "SysManage", "DepsManage")]
        public ActionResult Available(string ids)
        {
            if (!string.IsNullOrEmpty(ids))
            {
                var idarray = ids.Split(',');
                string sqlids = "'" + string.Join("','", idarray) + "'";
                string sql = "update SysDep set isavailable=1,UpdateDate=GETDATE(),UpdateBy='" + cuser.UserID + "',UpdateByName='" + cuser.LoginName + "' where id in (" + sqlids + ")";
                if (depService.ExecuteSql(sql, out msg) > 0)
                {
                    return Json(new AjaxResult() { success = true, msg = AvailableSuccess, url = Url.Action("treeindex") });
                }
                else
                {
                    msg = errorOutPutToPage ? msg : AvailableFailure;
                    return Json(new AjaxResult() { success = false, msg = msg });
                }
            }
            else
            {
                return Json(new AjaxResult() { success = false, msg = didnotchoosedata });
            }
        }
        [LSAuthorize("DepUnAvailable", "SysManage", "DepsManage")]
        public ActionResult UnAvailable(string ids)
        {
            if (!string.IsNullOrEmpty(ids))
            {
                var idarray = ids.Split(',');
                string sqlids = "'" + string.Join("','", idarray) + "'";
                string sql = "update SysDep set isavailable=0,UpdateDate=GETDATE(),UpdateBy='" + cuser.UserID + "',UpdateByName='" + cuser.LoginName + "' where id in (" + sqlids + ")";
                if (depService.ExecuteSql(sql, out msg) > 0)
                {
                    return Json(new AjaxResult() { success = true, msg = UnAvailableSuccess, url = Url.Action("treeindex") });
                }
                else
                {
                    msg = errorOutPutToPage ? msg : UnAvailableFailure;
                    return Json(new AjaxResult() { success = false, msg = msg });
                }
            }
            else
            {
                return Json(new AjaxResult() { success = false, msg = didnotchoosedata });
            }
        }        
    }
}

L.S.Home/Areas/admin/Controllers/SysUserController.cs
using Autofac;
using L.S.Common;
using L.S.Home.Models;
using L.S.Interface;
using L.S.Interface.BLL;
using L.S.Model.DatabaseModel.Entity;
using L.Study.Common;
using L.Study.Common.Cache;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace L.S.Home.Areas.admin.Controllers
{
    
    public class SysUserController : LsBaseController
    {
        //userService中有DbContext，然而都是autofac注入的，似乎不需要在每一个controller里写dispose方法来调用BaseService的dispose方法，因为我怎么看，也不是每刷新一下页面sqlserver的实时连接数就加1
        public IUserService userService;
        public IDepService depService;
        private IRoleBLL roleBll;
        public SysUserController(IUserService _userService, IDepService _depService,IRoleBLL _roleBLL)
        {
            userService = _userService;
            depService = _depService;            
            roleBll = _roleBLL;
        }

        #region 用户管理
        [LSAuthorize("UsersManage", "SysManage", "UsersManage")]
        public ActionResult Index(int page = 1, int pageSize = 10)
        {
            if (page <= 0) { page = 1; }
            var list = userService.GetPagedList(su => true, page, pageSize, modellist => modellist.OrderByDescending(su => su.ID));
            return View(list);
        }

        [LSAuthorize("UserCreate", "SysManage", "UsersManage")]
        public ActionResult Create()
        {
            return View();
        }

        [LSAuthorize("UserCreate", "SysManage", "UsersManage")]
        [HttpPost]
        public ActionResult Create(SysUser model, string SysRolesID)
        {
            SysUser u = model;
            u.ID = IdentityCreator.NextIdentity;
            u.AddBy = cuser.UserID;
            u.AddByName = cuser.LoginName;
            u.AddDate = DateTime.Now;
            if (!userService.Exist(user => user.LoginName == model.LoginName))
            {
                var dep = depService.Find(u.SysDepID);
                if (dep != null)
                {
                    u.SysDepName = dep.Name;
                    userService.Add(u);
                    if (userService.SaveChanges(out msg) > 0)
                    {
                        if (roleBll.SetUserRoles(model.ID, SysRolesID, out msg))
                        {
                            return Json(new AjaxResult() { success = true, msg = insertSuccess, url = Url.Action("Index"), moremsg = msg });
                        }
                        else
                        {
                            return Json(new AjaxResult() { success = false, msg = msg });
                        }
                    }
                    else
                    {
                        msg = errorOutPutToPage ? msg : insertFailure;
                        return Json(new AjaxResult() { success = false, msg = msg });
                    }
                }
                else
                {
                    return Json(new AjaxResult() { success = false, msg = "未找到对应的部门" });
                }
            }
            else
            {
                return Json(new AjaxResult() { success = false, msg = "登录名已存在" });
            }
        }

        [LSAuthorize("UserEdit", "SysManage", "UsersManage")]
        public ActionResult Edit(string id)
        {            
            if (!string.IsNullOrEmpty(id))
            {
                SysUser user = userService.Find(u => u.ID == id);
                var userRolesInfo=user.SysUserRoles.Select(ur => new { ur.SysRole.Name, ur.SysRole.ID ,RightLists=ur.SysRole.SysRoleRights.Select(rr=>rr.SysRight.Name)}).ToList();
                ViewBag.roleNameStr = string.Join(",", userRolesInfo.Select(r=>r.Name).ToArray());
                ViewBag.roleIDStr = string.Join(",", userRolesInfo.Select(r => r.ID).ToArray());
                ViewBag.UserRights = string.Join(",", userRolesInfo.SelectMany(r => r.RightLists).Distinct().ToArray());
                return View(user);
            }
            else
            {
                return View("_NoDataInLayout");
            }
        }
        [LSAuthorize("UserEdit", "SysManage", "UsersManage")]
        [HttpPost]
        public ActionResult Edit(SysUser model,string SysRolesID)
        {
            if (!string.IsNullOrEmpty(model.ID))
            {
                model.UpdateBy = cuser.UserID;
                model.UpdateByName = cuser.LoginName;
                model.UpdateDate = DateTime.Now;
                var dep = depService.Find(model.SysDepID);
                if (dep != null)
                {
                    model.SysDepName = dep.Name;
                    userService.Update(model);
                    var result = userService.SaveChanges(out msg);
                    if (result > 0)
                    {
                        if (roleBll.SetUserRoles(model.ID, SysRolesID, out msg))
                        {
                            CacheMaker.RedisCache.Remove("sidkey" + model.ID);
                            return Json(new AjaxResult() { success = true, msg = updateSuccess, url = Url.Action("Index") });
                        }
                        else
                        {
                            return Json(new AjaxResult() { success = false, msg = msg });
                        }
                    }
                    else
                    {
                        msg = errorOutPutToPage ? msg : updateFailure;
                        return Json(new AjaxResult() { success = false, msg = msg });
                    }
                }
                else
                {
                    return Json(new AjaxResult() { success = false, msg = "未找到对应的部门" });
                }
            }

            else
            {
                return View("_NoDataInLayout");
            }
            
        }

        [LSAuthorize("UserDelete", "SysManage", "UsersManage")]
        public ActionResult Delete(string ids)
        {
            if (!string.IsNullOrEmpty(ids))
            {
                if (userService.UsersDelete(ids, out msg) > 0)
                {
                    return Json(new AjaxResult() { success = true, msg = deleteSuccess, url = Url.Action("Index") });
                }
                else
                {
                    msg = errorOutPutToPage ? msg : deleteFailure;
                    return Json(new AjaxResult() { success = false, msg = msg });
                }
            }
            else
            {
                return Json(new AjaxResult() { success = false, msg = didnotchoosedata });
            }
        }

        [LSAuthorize("UserAvailable", "SysManage", "UsersManage")]
        public ActionResult Available(string ids)
        {
            if (!string.IsNullOrEmpty(ids))
            {
                var idarray = ids.Split(',');
                string sqlids = "'" + string.Join("','", idarray) + "'";
                string sql = "update SysUser set isavailable=1,UpdateDate=GETDATE(),UpdateBy='" + cuser.UserID + "',UpdateByName='" + cuser.LoginName + "' where id in (" + sqlids + ")";
                if (userService.ExecuteSql(sql, out msg) > 0)
                {
                    return Json(new AjaxResult() { success = true, msg = AvailableSuccess, url = Url.Action("index") });
                }
                else
                {
                    msg = errorOutPutToPage ? msg : AvailableFailure;
                    return Json(new AjaxResult() { success = false, msg = msg });
                }
            }
            else
            {
                return Json(new AjaxResult() { success = false, msg = didnotchoosedata });
            }
        }
        [LSAuthorize("UserUnAvailable", "SysManage", "UsersManage")]
        public ActionResult UnAvailable(string ids)
        {
            if (!string.IsNullOrEmpty(ids))
            {
                var idarray = ids.Split(',');
                string sqlids = "'" + string.Join("','", idarray) + "'";
                string sql = "update SysUser set isavailable=0,UpdateDate=GETDATE(),UpdateBy='" + cuser.UserID + "',UpdateByName='" + cuser.LoginName + "' where id in (" + sqlids + ")";
                if (userService.ExecuteSql(sql, out msg) > 0)
                {
                    return Json(new AjaxResult() { success = true, msg = UnAvailableSuccess, url = Url.Action("index") });
                }
                else
                {
                    msg = errorOutPutToPage ? msg : UnAvailableFailure;
                    return Json(new AjaxResult() { success = false, msg = msg });
                }
            }
            else
            {
                return Json(new AjaxResult() { success = false, msg = didnotchoosedata });
            }
        }
        #endregion
    }
}

L.S.Home/Areas/admin/Views/SysDep/Create.cshtml
@model SysDep
@{
    ViewBag.Title = "部门添加";
}
<div>
    <ul class="breadcrumb admin-bread-ul">
        <li><a href="@Url.Action("Index","SysUser")">系统管理</a> <span class="divider">/</span></li>
        <li><a href="@Url.Action("Index","SysDep")">部门管理</a> <span class="divider">/</span></li>
        <li class="active">部门添加</li>
    </ul>
</div>
@using (Ajax.BeginForm("Create", null, new AjaxOptions() { HttpMethod = "Post", OnBegin = "LS.admin.myfn.AjaxBegin('#form0')", OnSuccess = "LS.admin.myfn.AjaxSuccess" }, new { @class = "form-horizontal admin-form" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">                
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="control-group">
            <label for="Name" class="control-label">部门名称</label>
            <div class="controls">
                <input type="text" maxlength="16" name="Name" placeholder="名称" validate min="2" max="10">
                <span class="ls-msg help-inline"></span>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">上级部门</label>
            <div class="controls">
                <span class="treetext" id="ParentName"></span>
                <a class="btn" onclick="LS.admin.myfn.dialogeopendeptree({id:'ParentID',name:'ParentName'},'@Url.Action("GetDepTree", "Async", new { Area = ""})');">请选择</a>
                <a class="btn clearselectedtree" onclick="$(this).siblings('.treevalue').val(''); $(this).siblings('.treetext').text('');">清空</a>
                <input class="treevalue" type="hidden" name="ParentID" id="ParentID" validate min="2" max="36" msg="请选择上级部门"/>
                <span class="ls-msg help-inline"></span>
            </div>
        </div>
        <div class="control-group">
            <div class="controls">
                <label class="checkbox">
                    <input type="checkbox" name="IsAvailable" value="true" checked="checked">启用
                </label>
            </div>
        </div>
        <div class="form-actions">
            <button class="btn btn-primary" type="submit" data-loading-text="提交中" data-complete-text="完成"><i class="icon-ok icon-white"></i>保存</button>
            <button class="btn" type="button" onclick="history.go(-1);">返回</button>
        </div>
    </div>
}

L.S.Home/Areas/admin/Views/SysDep/Delete.cshtml
@model L.S.Model.DatabaseModel.Entity.SysDep

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SysDep</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AddBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AddBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AddDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AddDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdateBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdateBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdateDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdateDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsAvailable)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsAvailable)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsDel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsDel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

L.S.Home/Areas/admin/Views/SysDep/DepList_Pa.cshtml
@model PagedList.IPagedList<SysDep>
@if (Model != null && Model.Count > 0)
{
    <div class=" ls-tablecontainer">
        <table class="table ls-table ls-table-hover-bright">
            <thead>
                <tr>
                    <th style="width:3%">
                        <input type="checkbox" class="ls-table-selectall" />
                    </th>
                    <th>
                        部门名称
                    </th>
                    <th>
                        添加人
                    </th>
                    <th>
                        添加日期
                    </th>
                    <th>
                        修改人
                    </th>
                    <th>
                        修改日期
                    </th>
                    <th>
                        启用
                    </th>
                    <th>
                        删除
                    </th>

                    <th style="width:8%">操作</th>
                </tr>
            </thead>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        <input type="checkbox" class="ls-table-selecttr" value="@item.ID" />
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.AddBy)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.AddDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UpdateBy)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UpdateDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.IsAvailable)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.IsDel)
                    </td>

                    <td>
                        <div class="btn-group">
                            @foreach (SysRight r in ViewBag.pageRightRightList)
                            {
                                if (r.ActionType == "View")
                                {
                                    <a class="btn btn-primary" href="@r.MenuUrl/@item.ID" )>@r.DisplayName</a>
                                }
                                else
                                {
                                    <a class="btn btn-primary ls-table-@r.ActionType.ToLower()" url="@r.MenuUrl/@item.ID" )>@r.DisplayName</a>
                                }
                            }
                        </div>
                    </td>
                </tr>
            }

        </table>
    </div>
    Html.RenderPartial("Pager_admin", Model);
}
else
{
    Html.RenderPartial("_NoData");
}

L.S.Home/Areas/admin/Views/SysDep/Details.cshtml
@model L.S.Model.DatabaseModel.Entity.SysDep

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>SysDep</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AddBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AddBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AddDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AddDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdateBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdateBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdateDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdateDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsAvailable)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsAvailable)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsDel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsDel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

L.S.Home/Areas/admin/Views/SysDep/Edit.cshtml
@model SysDep
@{
    ViewBag.Title = "部门编辑";
}
<div>
    <ul class="breadcrumb admin-bread-ul">
        <li><a href="@Url.Action("Index","SysUser")">系统管理</a> <span class="divider">/</span></li>
        <li><a href="@Url.Action("Index","SysDep")">部门管理</a> <span class="divider">/</span></li>
        <li class="active">部门编辑</li>
    </ul>
</div>
@using (Ajax.BeginForm("Edit", null, new AjaxOptions() { HttpMethod = "Post", OnBegin = "LS.admin.myfn.AjaxBegin('#form0')", OnSuccess = "LS.admin.myfn.AjaxSuccess" }, new { @class = "form-horizontal admin-form" }))
{
    @Html.AntiForgeryToken()
    <input type="hidden" value="@Model.ID" name="ID"/>
    <input type="hidden" value="@Model.AddBy" name="AddBy" />
    <input type="hidden" value="@Model.AddByName" name="AddByName" />
    <input type="hidden" value="@Model.AddDate" name="AddDate" />
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="control-group">
            <label for="Name" class="control-label">部门名称</label>
            <div class="controls">
                <input type="text" maxlength="16" name="Name" placeholder="名称" validate min="2" max="10" value="@Model.Name">
                <span class="ls-msg help-inline"></span>
            </div>
        </div>
        @if (Model.ID != "root")
        {
        <div class="control-group">
            <label class="control-label">上级部门</label>
            <div class="controls">
                <span class="treetext" id="ParentName">@Model.ParentName</span>
                <a class="btn" onclick="LS.admin.myfn.dialogeopendeptree({id:'ParentID',name:'ParentName'},'@Url.Action("GetDepTree", "Async", new { Area = "", thisid = Model.ID })');">请选择</a>
                <a class="btn clearselectedtree" onclick="$(this).siblings('.treevalue').val(''); $(this).siblings('.treetext').text('');">清空</a>
                <input class="treevalue" type="hidden" name="ParentID" id="ParentID" value="@Model.ParentID" validate min="2" max="36" msg="请选择上级部门"/>
                <span class="ls-msg help-inline"></span>
            </div>
        </div>
        <div class="control-group">
            <div class="controls">
                <label class="checkbox">
                    @Html.CheckBox("IsAvailable", Model.IsAvailable)启用
                </label>
            </div>
        </div>
        }
        <div class="form-actions">
            <button class="btn btn-primary" type="submit" data-loading-text="提交中" data-complete-text="完成"><i class="icon-ok icon-white"></i>保存</button>
            <button class="btn" type="button" onclick="history.go(-1);">返回</button>
        </div>
    </div>
}

L.S.Home/Areas/admin/Views/SysDep/Index.cshtml
@model PagedList.IPagedList<SysDep>

@{
    ViewBag.Title = "部门管理";
}
<div>
    <ul class="breadcrumb admin-bread-ul">
        <li><a href="@Url.Action("Index","SysUser")">系统管理</a> <span class="divider">/</span></li>
        <li class="active">部门管理</li>
    </ul>
</div>
@foreach (SysRight r in ViewBag.pageTopRightList)
{
    if (r.ActionType == "View")
    {
        <a class="btn btn-primary" href="@r.MenuUrl" )>@r.DisplayName</a>
    }
    else
    {
        <a class="btn btn-primary ls-table-@r.ActionType.ToLower()" url="@r.MenuUrl" )>@r.DisplayName</a>
    }
}
@if (Model != null && Model.Count > 0)
{
    Html.RenderPartial("DepList_Pa");
}
else { Html.RenderPartial("_NoData"); }