L.S.Home/Areas/admin/Controllers/SysRoleController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using L.S.Model.DatabaseModel.Context;
using L.S.Model.DatabaseModel.Entity;
using L.S.Interface;
using L.S.Home.Models;
using L.Study.Common;
using Autofac;
using L.S.Interface.BLL;
using L.S.Common;
using L.S.Model.DomainModel.Sys;

namespace L.S.Home.Areas.admin.Controllers
{
    [LSAuthorize]
    public class SysRoleController : LsBaseController
    {
        private IRoleService roleService;
        private IRoleBLL roleBll;

        public SysRoleController(IRoleService _roleService,IRoleBLL _roleBLL)
        {
            roleService = _roleService;
            //roleBll = IocConfig.Container.Resolve<RoleBLL>();
            roleBll = _roleBLL;
        }

        [LSAuthorize("RolesManage", "SysManage", "RolesManage")]
        public ActionResult Index(int page = 1, int pageSize = 10)
        {
            var result = roleService.GetPagedList(r => true, page, pageSize, modellist => modellist.OrderByDescending(d => d.AddDate));
            return View(result);
        }

        [LSAuthorize("RolesManage", "SysManage", "RolesManage")]
        public ActionResult TreeIndex(int page = 1, int pageSize = 10)
        {
            return View();
        }

        [LSAuthorize("DepsManage", "SysManage", "DepsManage")]
        public ActionResult GetSysRole(string id)
        {
            var model = roleService.GetList(r => r.ID == id).Select(r => new SysRoleViewModel
            {
                ID = r.ID,
                Name = r.Name,
                ParentID = r.ParentID,
                ParentName = r.Parent == null ? "" : r.Parent.Name,
                IsAvailable = r.IsAvailable,
                AddBy = r.AddBy,
                AddDate = r.AddDate,
                DefaultHomePath=r.DefaultHomePath,
                SysRightsID = r.SysRoleRights.Select(rr=>rr.SysRight.ID).ToList(),
                SysRightsName = r.SysRoleRights.Select(rr => rr.SysRight.Name).ToList(),
                SortNo=r.SortNo,
            }).FirstOrDefault();
            return Json(model, JsonRequestBehavior.AllowGet);
        }

        [LSAuthorize("RoleCreate", "SysManage", "RolesManage")]
        public ActionResult Create()
        {
            return View(new SysRole());
        }

        // POST: admin/sysrole/Create
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 http://go.microsoft.com/fwlink/?LinkId=317598。
        [LSAuthorize("RoleCreate", "SysManage", "RolesManage")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IsAvailable,Name,ParentID,ParentName,DefaultHomePath,SortNo")] SysRole sysRole,string SysRightsID)
        {
            sysRole.ID = IdentityCreator.NextIdentity;
            sysRole.AddBy = cuser.UserID;
            sysRole.AddByName = cuser.LoginName;
            sysRole.AddDate = DateTime.Now;
            sysRole.IsDel = false;
            if (string.IsNullOrEmpty(Request["SortNo"])) { sysRole.SortNo = 0; }

            var parentRole = roleService.Find(sysRole.ParentID);
            if (parentRole != null)
            {
                if (sysRole.ID != "superadmin")
                {
                    var parentRolesRightIDList = parentRole.SysRoleRights.Select(srr => srr.RightID).Distinct().ToList();
                    var roleRightIDList = SysRightsID.Split(',').Where(s => !string.IsNullOrEmpty(s)).ToList();
                    var notallowed = roleRightIDList.Any(rid => !parentRolesRightIDList.Contains(rid));
                    if (notallowed)//如果所选权限里有一个是上级角色所没有的，就表示所选的上级角色权限太小了，将不允许保存
                    {
                        return Json(new AjaxResult() { success = false, msg = insertFailure + "，所选上级角色的权限小于为此角色所选择的权限", moremsg = msg });
                    }
                    else
                    {
                        sysRole.ParentName = parentRole.Name;
                        sysRole.Level = parentRole.Level + 1;
                        sysRole.RoleIDPath = parentRole.RoleIDPath  + sysRole.ID + "/";
                        sysRole.RoleNamePath = parentRole.RoleNamePath  + sysRole.Name + "/";
                    }
                }
                roleService.Add(sysRole);
                if (roleService.SaveChanges(out msg) > 0)//这里不提交，把提交放到下面的SetRoleRights方法（方法里有调用SaveChange）里看是否可行，事实证明是可行的，然并卵！
                {
                    if (roleBll.SetRoleRights(sysRole.ID, SysRightsID, out msg))
                    {
                        return Json(new AjaxResult() { success = true, msg = insertSuccess, url = Url.Action("treeindex", "sysrole", new { area = "admin" }), moremsg = msg });
                    }
                    else
                    {
                        roleService.Remove(sysRole);
                        roleService.SaveChanges(out msg);//妈的，要是SetRoleRights执行失败了，这里还要手动删除一下刚才插入的SysRole记录。你问我为什么不能放在一个事务里插入SysRole和此角色的权限？因为角色权限有一个字段作为外键关联的SysRole的ID！！
                        return Json(new AjaxResult() { success = false, msg = insertFailure, moremsg = msg });
                    }
                }
                else
                {
                    return Json(new AjaxResult() { success = false, msg = insertFailure, moremsg = msg });
                }
            }
            else
            {
                return Json(new AjaxResult() { success = false, msg = "未找到上级角色，保存失败", moremsg = msg });
            }
        }

        [LSAuthorize("RoleEdit", "SysManage", "RolesManage")]
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SysRole sysRole = roleService.Find(id);
            if (sysRole == null)
            {
                return View("_NoDataInLayout");
            }
            SysRole parent = sysRole.Parent;
            if (parent != null)
            {
                ViewBag.ParentRoleNameStr = parent.Name;
                ViewBag.ParentRoleIDStr = parent.ID;
            }
            var rightList = sysRole.SysRoleRights.Select(a => new { a.SysRight.Name ,a.SysRight.ID}).ToList();
            var rightIDStr=string.Join(",",rightList.Select(r => r.ID).ToArray());
            var rightNameStr = string.Join(",", rightList.Select(r => r.Name).ToArray());
            ViewBag.rightIDStr = rightIDStr;
            ViewBag.rightNameStr = rightNameStr;
            return View(sysRole);
        }

        [LSAuthorize("RoleEdit", "SysManage", "RolesManage")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,AddBy,AddByName,AddDate,IsAvailable,Name,ParentID,ParentName,DefaultHomePath,SortNo")] SysRole sysRole,string SysRightsID)
        {
            var tmpList= roleService.GetQueryable(role=>role.ID==sysRole.ID).SelectMany(role=>role.SysRoleRights.Select(roleright=>roleright.RightID)).ToList();
            bool rightIncrease = !tmpList.Any(tr => !SysRightsID.Contains(tr));//数据库中的此角色的权限，无任何一个未选，则表示权限未降低
            
            bool allowedModify = rightIncrease || sysRole.ID != "superadmin";
            if (allowedModify)
            {
                #region 除系统内置的超级管理员，其他角色可以修改
                sysRole.UpdateBy = cuser.UserID;
                sysRole.UpdateByName = cuser.LoginName;
                sysRole.UpdateDate = DateTime.Now;
                sysRole.IsDel = false;
                if (string.IsNullOrEmpty(Request["SortNo"])) { sysRole.SortNo = 0; }
                var parentRole = roleService.Find(sysRole.ParentID);
                if (parentRole != null || sysRole.ID == "superadmin")
                {
                    if (sysRole.ID != "superadmin")
                    {
                        var parentRolesRightIDList = parentRole.SysRoleRights.Select(srr => srr.RightID).Distinct().ToList();
                        var roleRightIDList = SysRightsID.Split(',').Where(s=>!string.IsNullOrEmpty(s)).ToList();
                        var notallowed = roleRightIDList.Any(rid => !parentRolesRightIDList.Contains(rid));
                        if (notallowed)//如果所选权限里有一个是上级角色所没有的，就表示所选的上级角色权限太小了，将不允许保存
                        {
                            return Json(new AjaxResult() { success = false, msg = updateFailure + "，所选上级角色的权限小于为此角色所选择的权限", moremsg = msg });
                        }
                        else
                        {
                            sysRole.ParentName = parentRole.Name;
                            sysRole.Level = parentRole.Level + 1;
                            sysRole.RoleIDPath = parentRole.RoleIDPath  + sysRole.ID + "/";
                            sysRole.RoleNamePath = parentRole.RoleNamePath  + sysRole.Name + "/";
                        }
                    }
                    else
                    {
                        sysRole.RoleIDPath = "/" + sysRole.ID + "/";
                        sysRole.RoleNamePath = "/" + sysRole.Name + "/";
                        sysRole.Level = 0;
                    }
                    roleService.Update(sysRole);
                    if (roleService.SaveChanges(out msg) > 0)
                    {
                        if (roleBll.SetRoleRights(sysRole.ID, SysRightsID, out msg))
                        {
                            return Json(new AjaxResult() { success = true, msg = updateSuccess, url = Url.Action("treeindex", "sysrole", new { area = "admin" }), moremsg = msg });
                        }
                        else
                        {
                            return Json(new AjaxResult() { success = false, msg = updateFailure, moremsg = msg });
                        }
                    }
                    else
                    {
                        return Json(new AjaxResult() { success = false, msg = updateFailure, moremsg = msg });
                    }

L.S.Home/Areas/admin/Views/SysRole/Create.cshtml
@model SysRole
@{
    ViewBag.Title = "角色添加";
}
<div>
    <ul class="breadcrumb admin-bread-ul">
        <li><a href="@Url.Action("Index","SysUser")">系统管理</a> <span class="divider">/</span></li>
        <li><a href="@Url.Action("Index","SysRole")">角色管理</a> <span class="divider">/</span></li>
        <li class="active">角色添加</li>
    </ul>
</div>
@using (Ajax.BeginForm("Create", null, new AjaxOptions() { HttpMethod = "Post", OnBegin = "LS.admin.myfn.AjaxBegin('#form0')", OnSuccess = "LS.admin.myfn.AjaxSuccess", OnFailure = "LS.admin.myfn.AjaxFailure" }, new { @class = "form-horizontal admin-form" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="control-group">
            <label for="Name" class="control-label">角色名称</label>
            <div class="controls">
                <input class="" type="text" name="Name" id="Name" value="@Model.Name" validate min="2" max="10"/>
                <span class="ls-msg help-inline"></span>
            </div>
        </div>
        <div class="control-group">
            <label for="Type" class="control-label">上级角色</label>
            <div class="controls">
                <span class="treetext" id="ParentRoleName"></span>
                <a class="btn" onclick="LS.admin.myfn.dialogeopenroletree({id:'ParentID',name:'ParentRoleName',toggledisplay:true,toggleselect:false,multiple:false},'@Url.Action("GetRoleTree", "Async", new { Area = "" ,thisid=Model.ID})');">请选择</a>
                <a class="btn clearselectedtree" onclick="$(this).siblings('.treevalue').val(''); $(this).siblings('.treetext').text('');">清空</a>
                <input class="treevalue" type="hidden" name="ParentID" id="ParentID" value="" validate min="2" max="36" msg="请选择上级角色" />
                <span class="ls-msg help-inline"></span>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">角色权限</label>
            <div class="controls">
                <span class="treetext" id="SysRightsName">@ViewBag.rightNameStr</span>
                <a class="btn" onclick="LS.admin.myfn.dialogeopenrighttree({id:'SysRightsID',name:'SysRightsName',toggledisplay:true,toggleselect:true},'@Url.Action("GetRightTree", "Async", new { Area = "" })');">请选择</a>
                <a class="btn clearselectedtree" onclick="$(this).siblings('.treevalue').val(''); $(this).siblings('.treetext').text('');">清空</a>
                <input class="treevalue" type="hidden" name="SysRightsID" id="SysRightsID" value="@ViewBag.rightIDStr" validate min="2" msg="请为角色选择相应的权限"/>
                <span class="ls-msg help-inline"></span>
            </div>
        </div>
        <div class="control-group">
            <label for="Name" class="control-label">默认主页</label>
            <div class="controls">
                <input class="" type="text" name="DefaultHomePath" id="DefaultHomePath" validate max="50" />
                <span class="ls-msg help-inline"></span>
            </div>
        </div>
        <div class="control-group">
            <div class="controls">
                <label class="checkbox">
                    <input type="checkbox" name="IsAvailable" value="true" checked="checked">启用
                </label>
            </div>
        </div>
        <div class="form-actions">
            <button class="btn btn-primary" type="submit" data-loading-text="提交中" data-complete-text="完成"><i class="icon-ok icon-white"></i>保存</button>
            <button class="btn" type="button" onclick="history.go(-1);">返回</button>
        </div>
    </div>
}

L.S.Home/Areas/admin/Views/SysRole/Delete.cshtml
@model L.S.Model.DatabaseModel.Entity.SysRole

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>SysRole</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.AddBy)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.AddBy)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.AddByName)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.AddByName)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.AddDate)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.AddDate)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.UpdateBy)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.UpdateBy)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.UpdateByName)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.UpdateByName)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.UpdateDate)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.UpdateDate)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.IsAvailable)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.IsAvailable)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.IsDel)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.IsDel)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

L.S.Home/Areas/admin/Views/SysRole/Details.cshtml
@model L.S.Model.DatabaseModel.Entity.SysRole

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>SysRole</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.AddBy)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.AddBy)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.AddByName)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.AddByName)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.AddDate)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.AddDate)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.UpdateBy)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.UpdateBy)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.UpdateByName)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.UpdateByName)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.UpdateDate)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.UpdateDate)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.IsAvailable)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.IsAvailable)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.IsDel)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.IsDel)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

L.S.Home/Areas/admin/Views/SysRole/Edit.cshtml
@model SysRole
@{
    ViewBag.Title = "角色编辑";
}
<div>
    <ul class="breadcrumb admin-bread-ul">
        <li><a href="@Url.Action("Index","SysUser")">系统管理</a> <span class="divider">/</span></li>
        <li><a href="@Url.Action("Index","SysRole")">角色管理</a> <span class="divider">/</span></li>
        <li class="active">角色编辑</li>
    </ul>
</div>
@using (Ajax.BeginForm("Edit", null, new AjaxOptions() { HttpMethod = "Post", OnBegin = "LS.admin.myfn.AjaxBegin('#form0')", OnSuccess = "LS.admin.myfn.AjaxSuccess", OnFailure = "LS.admin.myfn.AjaxFailure" }, new { @class = "form-horizontal admin-form" }))
{
    @Html.AntiForgeryToken()
    <input type="hidden" value="@Model.ID" name="ID" />
    <input type="hidden" value="@Model.AddBy" name="AddBy" />
    <input type="hidden" value="@Model.AddByName" name="AddByName" />
    <input type="hidden" value="@Model.AddDate" name="AddDate" />

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="control-group">
            <label for="Name" class="control-label">角色名称</label>
            <div class="controls">
                <input class="" type="text" name="Name" id="Name" value="@Model.Name" validate min="2" max="10"/>
                <span class="ls-msg help-inline"></span>
            </div>
        </div>
        <div class="control-group">
            <label for="Type" class="control-label">上级角色</label>
            <div class="controls">
                <span class="treetext" id="ParentRoleName">@ViewBag.ParentRoleNameStr</span>
                <a class="btn" onclick="LS.admin.myfn.dialogeopenroletree({id:'ParentID',name:'ParentRoleName',toggledisplay:true,toggleselect:false,multiple:false},'@Url.Action("GetRoleTree", "Async", new { Area = "" ,thisid=Model.ID})');">请选择</a>
                <a class="btn clearselectedtree" onclick="$(this).siblings('.treevalue').val(''); $(this).siblings('.treetext').text('');">清空</a>
                @if (Model.ID == "superadmin")
                {
                    <input class="treevalue" type="hidden" name="ParentID" id="ParentID" value="@ViewBag.ParentRoleIDStr" />
                }
                else
                {
                    <input class="treevalue" type="hidden" name="ParentID" id="ParentID" value="@ViewBag.ParentRoleIDStr" validate min="2" max="36" msg="请选择上级角色" />
                }
                <span class="ls-msg help-inline"></span>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">角色权限</label>
            <div class="controls">
                <span class="treetext" id="SysRightsName">@ViewBag.rightNameStr</span>
                <a class="btn" onclick="LS.admin.myfn.dialogeopenrighttree({id:'SysRightsID',name:'SysRightsName',toggledisplay:true,toggleselect:true},'@Url.Action("GetRightTree", "Async", new { Area = "" })');" >请选择</a>
                <a class="btn clearselectedtree" onclick="$(this).siblings('.treevalue').val(''); $(this).siblings('.treetext').text('');">清空</a>
                <input class="treevalue" type="hidden" name="SysRightsID" id="SysRightsID" value="@ViewBag.rightIDStr" validate min="2" msg="请为角色选择相应的权限"/>
                <span class="ls-msg help-inline"></span>
            </div>
        </div>
        <div class="control-group">
            <label for="Name" class="control-label">默认主页</label>
            <div class="controls">
                <input class="" type="text" name="DefaultHomePath" id="DefaultHomePath" validate max="100" value="@Model.DefaultHomePath"/>
                <span class="ls-msg help-inline"></span>
            </div>
        </div>
        @if (Model.ID != "superadmin")
        {
        <div class="control-group">
            <div class="controls">
                <label class="checkbox">
                    @Html.CheckBox("IsAvailable", Model.IsAvailable)启用
                </label>
            </div>
        </div>
        }
        else
        {            
            @Html.Hidden("IsAvailable", Model.IsAvailable)
        }
        <div class="form-actions">
            <button class="btn btn-primary" type="submit" data-loading-text="提交中" data-complete-text="完成"><i class="icon-ok icon-white"></i>保存</button>
            <button class="btn" type="button" onclick="history.go(-1);">返回</button>
        </div>
    </div>
}

L.S.Home/Areas/admin/Views/SysRole/Index.cshtml
@model PagedList.IPagedList<SysRole>

@{
    ViewBag.Title = "角色管理";
}
<div>
    <ul class="breadcrumb admin-bread-ul">
        <li><a href="@Url.Action("Index","SysUser")">系统管理</a> <span class="divider">/</span></li>
        <li class="active">角色管理</li>
    </ul>
</div>
@foreach (SysRight r in ViewBag.pageTopRightList)
{
    if (r.ActionType == "View")
    {
        <a class="btn btn-primary" href="@r.MenuUrl" )>@r.DisplayName</a>
    }
    else
    {
        <a class="btn btn-primary ls-table-@r.ActionType.ToLower()" url="@r.MenuUrl" )>@r.DisplayName</a>
    }
}
@if (Model != null && Model.Count > 0)
{
    Html.RenderPartial("RoleList_Pa");
}
else { Html.RenderPartial("_NoData"); }

L.S.Home/Areas/admin/Views/SysRole/RoleList_Pa.cshtml
@model PagedList.IPagedList<SysRole>
@if (Model != null && Model.Count > 0)
{
    <div class=" ls-tablecontainer">
        <table class="table ls-table ls-table-hover-bright">
            <thead>
                <tr>
                    <th style="width:3%">
                        <input type="checkbox" class="ls-table-selectall" />
                    </th>
                    <th>
                        角色名称
                    </th>
                    <th>
                        上级角色ID
                    </th>
                    <th>
                        上级角色名称
                    </th>
                    <th>
                        添加人
                    </th>
                    <th>
                        添加日期
                    </th>
                    <th>
                        修改人
                    </th>
                    <th>
                        修改日期
                    </th>
                    <th>
                        启用
                    </th>
                    <th stle="width:8%;">操作</th>
                </tr>
            </thead>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        <input type="checkbox" class="ls-table-selecttr" value="@item.ID" />
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ParentID)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ParentName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.AddBy)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.AddDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UpdateBy)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UpdateDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.IsAvailable)
                    </td>
                    <td>
                        <div class="btn-group">
                            @foreach (SysRight r in ViewBag.pageRightRightList)
                            {
                                if (r.ActionType == "View")
                                {
                                    <a class="btn btn-primary" href="@r.MenuUrl/@item.ID" )>@r.DisplayName</a>
                                }
                                else
                                {
                                    <a class="btn btn-primary ls-table-@r.ActionType.ToLower()" url="@r.MenuUrl/@item.ID" )>@r.DisplayName</a>
                                }
                            }
                        </div>
                    </td>
                </tr>
            }

        </table>
    </div>
    Html.RenderPartial("Pager_admin", Model);
}
else
{
    Html.RenderPartial("_NoData");
}