L.S.Home/Areas/admin/Controllers/InfoController.cs
using L.S.Home.Models;
using L.S.Interface;
using L.S.Model.DatabaseModel.Entity;
using L.S.Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using L.Study.Common.Cache;
using L.S.Model.DomainModel;

namespace L.S.Home.Areas.admin.Controllers
{
    public class InfoController : LsBaseController
    {
        public IInfoService infoService;
        public ICategoryService cateService;
        public InfoController(IInfoService _infoService, ICategoryService _cateService)
        {
            infoService = _infoService;
            cateService = _cateService;
        }

        [LSAuthorize("InfoList", "InfoManage", "InfoList")]
        public ActionResult Index()
        {
            var list = infoService.GetPagedList(d => true, page, pageSize, modellist => modellist.OrderByDescending(d => d.AddDate));
            return View(list);
        }
        [LSAuthorize("InfoCreate", "InfoManage", "InfoList")]
        public ActionResult Create()
        {
            var InfoCategoryTypeList = CacheMaker.IISCache.GetOrSetThenGet("InfoCategoryType_Cache_Key", () =>
            {
                return cateService.GetQueryable(cate => cate.CateTypeID == "InfoCategoryType").Select(cate => new SelectListItem { Value = cate.ID, Text = cate.Name }).ToList();
            });
            ViewBag.InfoCategoryTypeList = InfoCategoryTypeList;
            return View();
        }
        [LSAuthorize("InfoCreate", "InfoManage", "InfoList")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Create([Bind(Include = "IsAvailable,Name,ImgPath,Introduction,Content,Source,Author,CategoryID")] Info info, string ImgPathToDelete = "")
        {
            int successCount = 0, notExistCount = 0;
            string msg = "";
            CommonUtil.RemoveFiles(ImgPathToDelete, out successCount, out notExistCount, out msg);
            info.ID = IdentityCreator.NextIdentity;
            info.AddBy = cuser.UserID;
            info.AddByName = cuser.LoginName;
            info.AddDate = DateTime.Now;
            info.IsDel = false;
            if (string.IsNullOrEmpty(Request["Introduction"]))
            {
                info.Introduction = info.Content.ToNoHtml().ToMaxString(200);
            }
            infoService.Add(info);
            if (infoService.SaveChanges(out msg) > 0)
            {
                return Json(new AjaxResult() { success = true, msg = insertSuccess, url = Url.Action("index", "info", "admin"), moremsg = msg });
            }
            else
            {
                return Json(new AjaxResult() { success = false, msg = insertFailure, moremsg = msg });
            }
        }

        [LSAuthorize("InfoEdit", "InfoManage", "InfoList")]
        public ActionResult Edit(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var InfoCategoryTypeList = CacheMaker.IISCache.GetOrSetThenGet("InfoCategoryType_Cache_Key", () =>
            {
                return cateService.GetQueryable(cate => cate.CateTypeID == "InfoCategoryType").Select(cate => new SelectListItem { Value = cate.ID, Text = cate.Name }).ToList();
            });
            ViewBag.InfoCategoryTypeList = InfoCategoryTypeList;
            InfoViewModel model = infoService.GetQueryable(i=>i.ID==id).Select(i=>new InfoViewModel
            {
                ID =i.ID,
                CategoryID = i.CategoryID,
                CategoryName = i.Category.Name,
                AddBy = i.AddBy,
                //AddByName = i.AddByUser.Name,
                AddDate = i.AddDate,
                Name=i.Name,
                ImgPath=i.ImgPath,
                Introduction=i.Introduction,
                Content=i.Content,
                Source=i.Source,
                Author=i.Author,
                IsAvailable=i.IsAvailable,
            }).FirstOrDefault();
            if (model == null)
            {
                return View("_NoDataInLayout");
            }
            return View(model);
        }
        [LSAuthorize("InfoEdit", "InfoManage", "InfoList")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Edit([Bind(Include = "ID,AddBy,AddByName,AddDate,IsAvailable,Name,Introduction,ImgPath,Content,Source,Author,CategoryID")] Info model,string ImgPathToDelete="")
        {
            int successCount = 0, notExistCount = 0;
            string msg = "";
            CommonUtil.RemoveFiles(ImgPathToDelete, out successCount, out notExistCount, out msg);
            model.UpdateBy = cuser.UserID;
            model.UpdateByName = cuser.LoginName;
            model.UpdateDate = DateTime.Now;
            if (string.IsNullOrEmpty(Request["Introduction"]))
            {
                model.Introduction = model.Content.ToNoHtml().ToMaxString(200);
            }
            infoService.Update(model);
            if (infoService.SaveChanges(out msg) > 0)
            {
                return Json(new AjaxResult() { success = true, msg = updateSuccess, url = Url.Action("index", "info", "admin"), moremsg = msg });
            }
            else
            {
                return Json(new AjaxResult() { success = false, msg = updateFailure, moremsg = msg });
            }
        }

        [LSAuthorize("InfoView", "InfoManage", "InfoList")]
        public ActionResult InfoView(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Info info = infoService.Find(id);            
            if (info == null)
            {
                return HttpNotFound();
            }
            return View(info);
        }

        [LSAuthorize("InfoDelete", "InfoManage", "InfoList")]
        [HttpPost]
        public ActionResult Delete(string ids)
        {
            if (!string.IsNullOrEmpty(ids))
            {
                if (infoService.InfoesDelete(ids, out msg) > 0)
                {
                    return Json(new AjaxResult() { success = true, msg = deleteSuccess, url = Url.Action("Index") });
                }
                else
                {
                    msg = errorOutPutToPage ? msg : deleteFailure;
                    return Json(new AjaxResult() { success = false, msg = msg });
                }
            }
            else
            {
                return Json(new AjaxResult() { success = false, msg = didnotchoosedata });
            }
        }
        [LSAuthorize("InfoAvailable", "InfoManage", "InfoList")]
        public ActionResult Available(string ids)
        {
            if (!string.IsNullOrEmpty(ids))
            {
                var idarray = ids.Split(',');
                string sqlids = "'" + string.Join("','", idarray) + "'";
                string sql = "update Info set isavailable=1,UpdateDate=GETDATE(),UpdateBy='"+cuser.UserID + "',UpdateByName='"+cuser.LoginName+"' where id in (" + sqlids + ")";
                if (infoService.ExecuteSql(sql, out msg) > 0)
                {
                    return Json(new AjaxResult() { success = true, msg = AvailableSuccess, url = Url.Action("index") });
                }
                else
                {
                    msg = errorOutPutToPage ? msg : AvailableFailure;
                    return Json(new AjaxResult() { success = false, msg = msg });
                }
            }
            else
            {
                return Json(new AjaxResult() { success = false, msg = didnotchoosedata });
            }
        }
        [LSAuthorize("InfoUnAvailable", "InfoManage", "InfoList")]
        public ActionResult UnAvailable(string ids)
        {
            if (!string.IsNullOrEmpty(ids))
            {
                var idarray = ids.Split(',');
                string sqlids = "'" + string.Join("','", idarray) + "'";
                string sql = "update Info set isavailable=0,UpdateDate=GETDATE(),UpdateBy='" + cuser.UserID + "',UpdateByName='" + cuser.LoginName + "' where id in (" + sqlids + ")";
                if (infoService.ExecuteSql(sql, out msg) > 0)
                {
                    return Json(new AjaxResult() { success = true, msg = UnAvailableSuccess, url = Url.Action("index") });
                }
                else
                {
                    msg = errorOutPutToPage ? msg : UnAvailableFailure;
                    return Json(new AjaxResult() { success = false, msg = msg });
                }
            }
            else
            {
                return Json(new AjaxResult() { success = false, msg = didnotchoosedata });
            }
        }
    }
}

L.S.Home/Areas/admin/Views/Info/Create.cshtml
@model SysDep
@{
    ViewBag.Title = "资讯添加";
}
<script src="/plugin/ueditor/ueditor.config.js"></script>
<script src="/plugin/ueditor/ueditor.all.min.js"></script>
<script src="/plugin/ueditor/lang/zh-cn/zh-cn.js"></script>

<link href="/uploadify/uploadify.css" rel="stylesheet" />
<script src="/uploadify/jquery.uploadify.min.js"></script>
<script>
        $(function () {
            var ue = UE.getEditor('Content');

            $("#ImgPath_file").uploadify({
                height: 30,
                swf: '/uploadify/uploadify.swf',
                formData: { 'fileType': 'InfoImg' },
                uploader: '/Async/UploadFile',
                buttonText: '选择图片',
                fileTypeExts: '*.gif; *.jpg; *.png',
                width: 220,
                'onUploadSuccess': function (file, data, response) {    
                    var filetext = $("#ImgPath").siblings(".file-name").text();
                    if (filetext == "") { filetext += file.name; }
                    else { filetext += "," + file.name; }
                    $("#ImgPath").siblings(".file-name").text(filetext);
                    var imgPathValue = $("#ImgPath").val();
                    if (imgPathValue == "") { imgPathValue += data; }
                    else { imgPathValue += "|" + data; }
                    $("#ImgPath").val(imgPathValue);
                    $("#ImgPath").siblings(".little-remind").before("<img class='info-img' src='" + data + "' />");

                    $(".info-img").on("click", infoImgClick);
                    $(".clear-file").show();
                }
            });

            var todelete = [];
            $(".clear-file").on("click", function () {
                var $this = $(this);
                var oldPathArray = $("#ImgPath").val().split("|");
                for (var i in oldPathArray) {
                    todelete.push(oldPathArray[i]);
                }
                $("#ImgPath").val("");
                $this.siblings(".file-name").text("");
                $this.siblings(".info-img").remove();
                $("#ImgPathToDelete").val(todelete.join("|"));
                $(".clear-file").hide();
            });
        });
        function infoImgClick(e) {
            var $this = $(this);
            var tmp_img = new Image();
            tmp_img.src = $this.attr("src");
            if ($this.css("width") == "30px") {
                $this.animate({ width: tmp_img.width, height: tmp_img.height }); //$this.animate({height:"auto"});
            } else {
                $this.animate({ width: "30px", height: "30px" });// $this.animate({ height: "30px" });
            }
            e.stopPropagation();
        }
</script>
<style>
    #Content{width:98%;min-height:500px;max-width:960px;}
    .info-img{width:30px;height:30px;margin:0 10px 0 0;}
</style>
<div>
    <ul class="breadcrumb admin-bread-ul">
        <li><a href="@Url.Action("Index","Info")">资讯</a> <span class="divider">/</span></li>
        <li><a href="@Url.Action("Index","Info")">资讯列表</a> <span class="divider">/</span></li>
        <li class="active">资讯添加</li>
    </ul>
</div>
@using (Ajax.BeginForm("Create", null, new AjaxOptions() { HttpMethod = "Post", OnBegin = "LS.admin.myfn.AjaxBegin('#form0')", OnSuccess = "LS.admin.myfn.AjaxSuccess" }, new { @class = "form-horizontal admin-form" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="control-group">
            <label for="Name" class="control-label">标题</label>
            <div class="controls">
                <input type="text" maxlength="20" name="Name" placeholder="标题" validate min="2" max="20">
                <span class="ls-msg help-inline"></span>
            </div>
        </div>
        <div class="control-group">
            <label for="Name" class="control-label">分类</label>
            <div class="controls">                
                @Html.DropDownList("CategoryID", ViewBag.InfoCategoryTypeList as IEnumerable<SelectListItem>, "--请选择分类--")
                <span class="ls-msg help-inline"></span>
            </div>
        </div>

        <div class="control-group">
            <label for="Name" class="control-label">图标</label>
            <div class="controls">
                <span class="file-name"></span>
                <input type="hidden" name="ImgPath" id="ImgPath" validate max="2000"/>
                <input type="file" maxlength="20" name="ImgPath_file" id="ImgPath_file" placeholder="图标" >   
                <input type="button" class="clear-file btn" value="清空" style="display:none;"/>
                <input type="hidden" name="ImgPathToDelete" id="ImgPathToDelete" />
                <span class="ls-msg help-inline"></span>                
                <span class="little-remind">@*（如果不选择图标，将会取内容里第一张图片作为此项保存）*@</span>
            </div>
        </div>
        <div class="control-group">
            <label for="Introduction" class="control-label">简介/导读</label>
            <div class="controls">                
                <textarea name="Introduction" maxlength="200" style="width: 38%;" id="Introduction" placeholder="简介/导读" validate max="200" cols="100" rows="5"></textarea><br />（此项如果不填写，将会从内容中取前200字符串作为简介保存）
                <span class="ls-msg help-inline"></span>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">内容</label>
            <div class="controls">
                <textarea name="Content" id="Content" validate min="1" cols="200" rows="15"></textarea>
                <span class="ls-msg help-inline"></span>
            </div>
        </div>
        <div class="control-group">
            <label for="Source" class="control-label">来源</label>
            <div class="controls">
                <input type="text" maxlength="100" name="Source" placeholder="来源" validate min="2" max="100">
                <span class="ls-msg help-inline"></span>
            </div>
        </div>
        <div class="control-group">
            <label for="Author" class="control-label">作者</label>
            <div class="controls">
                <input type="text" maxlength="10" name="Author" placeholder="标题" validate min="2" max="10">
                <span class="ls-msg help-inline"></span>
            </div>
        </div>
        <div class="control-group">
            <div class="controls">
                <label class="checkbox">
                    <input type="checkbox" name="IsAvailable" value="true" checked="checked">启用
                </label>
            </div>
        </div>
        <div class="form-actions">
            <button class="btn btn-primary" type="submit" data-loading-text="提交中" data-complete-text="完成"><i class="icon-ok icon-white"></i>保存</button>
            <button class="btn" type="button" onclick="history.go(-1);">返回</button>
        </div>
    </div>
}

L.S.Home/Areas/admin/Views/Info/Edit.cshtml
@model InfoViewModel
@{
    ViewBag.Title = "资讯编辑";
}
<script src="/plugin/ueditor/ueditor.config.js"></script>
<script src="/plugin/ueditor/ueditor.all.min.js"></script>
<script src="/plugin/ueditor/lang/zh-cn/zh-cn.js"></script>

<link href="/uploadify/uploadify.css" rel="stylesheet" />
<script src="/uploadify/jquery.uploadify.min.js"></script>
<script>
        $(function () {
            var ue = UE.getEditor('Content');
            
            $("#ImgPath_file").uploadify({
                height: 30,
                swf: '/uploadify/uploadify.swf',
                formData: { 'fileType': 'InfoImg' },
                uploader: '/Async/UploadFile',
                buttonText: '选择图片',
                fileTypeExts: '*.gif; *.jpg; *.png',
                width: 220,
                'onUploadSuccess': function (file, data, response) {
                    var filetext = $("#ImgPath").siblings(".file-name").text();
                    if (filetext == "") { filetext += file.name; }
                    else { filetext += "," + file.name; }
                    $("#ImgPath").siblings(".file-name").text(filetext);
                    var imgPathValue = $("#ImgPath").val();
                    if (imgPathValue == "") { imgPathValue += data; }
                    else { imgPathValue += "|" + data; }
                    $("#ImgPath").val(imgPathValue);
                    $("#ImgPath").siblings(".little-remind").before("<img class='info-img' src='" + data + "' />");

                    $(".info-img").on("click", infoImgClick);
                    $(".clear-file").show();
                }
            });

            $(".info-img").on("click", infoImgClick);

            var todelete = [];
            $(".clear-file").on("click", function () {
                var $this = $(this);                
                var oldPathArray = $("#ImgPath").val().split("|");
                for (var i in oldPathArray) {
                    todelete.push(oldPathArray[i]);
                }
                $("#ImgPath").val("");
                $this.siblings(".file-name").text("");
                $this.siblings(".info-img").remove();
                $("#ImgPathToDelete").val(todelete.join("|"));
                $(".clear-file").hide();
            });
        });
        function infoImgClick(e) {
            var $this = $(this);
            var tmp_img = new Image();
            tmp_img.src = $this.attr("src");
            if ($this.css("width") == "30px") {
                $this.animate({ width: tmp_img.width, height: tmp_img.height }); //$this.animate({height:"auto"});
            } else {
                $this.animate({ width: "30px", height: "30px" });// $this.animate({ height: "30px" });
            }
            e.stopPropagation();
        }
</script>
<style>
    #Content {
        width: 98%;
        min-height: 500px;
        max-width: 960px;
    }
    .info-img{width:30px;height:30px;margin:0 10px 0 0;}
</style>
<div>
    <ul class="breadcrumb admin-bread-ul">
        <li><a href="@Url.Action("Index","Info")">资讯</a> <span class="divider">/</span></li>
        <li><a href="@Url.Action("Index","Info")">资讯列表</a> <span class="divider">/</span></li>
        <li class="active">资讯编辑</li>
    </ul>
</div>
@using (Ajax.BeginForm("Edit", null, new AjaxOptions() { HttpMethod = "Post", OnBegin = "LS.admin.myfn.AjaxBegin('#form0')", OnSuccess = "LS.admin.myfn.AjaxSuccess" }, new { @class = "form-horizontal admin-form" }))
{
    @Html.AntiForgeryToken()
    <input type="hidden" value="@Model.ID" name="ID" />
    <input type="hidden" value="@Model.AddBy" name="AddBy" />
    @*<input type="hidden" value="@Model.AddByName" name="AddByName" />*@
    <input type="hidden" value="@Model.AddDate" name="AddDate" />

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="control-group">
            <label for="Name" class="control-label">标题</label>
            <div class="controls">
                <input type="text" maxlength="20" name="Name" placeholder="标题" validate min="2" max="20" value="@Model.Name">
                <span class="ls-msg help-inline"></span>
            </div>
        </div>
        @*<div class="control-group">
            <label for="Name" class="control-label">分类</label>
            <div class="controls">
                @Html.DropDownList("CategoryID", ViewBag.InfoCategoryTypeList as IEnumerable<SelectListItem>, "--请选择分类--" )
                <span class="ls-msg help-inline"></span>
            </div>
        </div>*@
        <div class="control-group">
            <label class="control-label">分类</label>
            <div class="controls">
                <span class="treetext" id="CategoryName">@Model.CategoryName</span>
                <a class="btn" url="@Url.Action("GetCategoryTree", "Async", new { Area = "" ,selectNodeID=Model.CategoryID,cateTypeID= "InfoCategoryType" })"
                   onclick="var url=$(this).attr('url');LS.admin.myfn.dialogeopencategorytree({id:'CategoryID',name:'CategoryName',toggledisplay:true,multiple:false},url);">请选择</a>
                <a class="btn clearselectedtree" onclick="$(this).siblings('.treevalue').val(''); $(this).siblings('.treetext').text('');">清空</a>
                <input class="treevalue" type="hidden" name="CategoryID" id="CategoryID" value="@Model.CategoryID" />
                <span class="ls-msg help-inline"></span>
            </div>
        </div>
        <div class="control-group">
            <label for="Name" class="control-label">图标</label>
            <div class="controls">
                @{ 
                    List<string> tmp = new List<string>();
                    if (!string.IsNullOrEmpty(Model.ImgPath))
                    {
                        var t1 = Model.ImgPath.Split('|');
                        foreach (var t in t1)
                        {
                            tmp.Add(t.Split('[')[1].Split(']')[0]);
                        }
                    }
                }
                <span class="file-name">@(string.IsNullOrEmpty(Model.ImgPath) ? "" :string.Join(",", tmp)) </span>
                <input type="hidden" name="ImgPath" id="ImgPath" validate max="2000" value="@Model.ImgPath" />
                <input type="file" maxlength="20" name="ImgPath_file" id="ImgPath_file" placeholder="图标">
                <input type="button" class="clear-file btn" value="清空" @if(string.IsNullOrEmpty(Model.ImgPath)){<text>style='display:none;'</text> } />
                <input type="hidden" name="ImgPathToDelete" id="ImgPathToDelete"/>
                <span class="ls-msg help-inline"></span>
                @if (!string.IsNullOrEmpty(Model.ImgPath))
                {
                    foreach (string s in Model.ImgPath.Split('|'))
                    {
                        if (!string.IsNullOrEmpty(s))
                        {
                        <img class="info-img" src="@s" />
                        }
                }
                }
                <span class="little-remind">@*（如果不选择图标，将会取内容里第一张图片作为此项保存）*@</span>
            </div>
        </div>
        <div class="control-group">
            <label for="Introduction" class="control-label">简介/导读</label>
            <div class="controls">
                <textarea name="Introduction" maxlength="200" style="width: 38%;" id="Introduction" placeholder="简介/导读" validate max="200" cols="100" rows="5">@Model.Introduction</textarea><br />（此项如果不填写，将会从内容中取前200字符串作为简介保存）
                <span class="ls-msg help-inline"></span>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">内容</label>
            <div class="controls">
                <textarea name="Content" id="Content" validate min="1" cols="200" rows="15">@Model.Content</textarea>
                <span class="ls-msg help-inline"></span>
            </div>
        </div>
        <div class="control-group">
            <label for="Source" class="control-label">来源</label>
            <div class="controls">
                <input type="text" maxlength="100" name="Source" placeholder="来源" validate min="2" max="100" value="@Model.Source">
                <span class="ls-msg help-inline"></span>
            </div>
        </div>
        <div class="control-group">
            <label for="Author" class="control-label">作者</label>
            <div class="controls">
                <input type="text" maxlength="10" name="Author" placeholder="标题" validate min="2" max="10" value="@Model.Author">
                <span class="ls-msg help-inline"></span>
            </div>
        </div>
        <div class="control-group">
            <div class="controls">
                <label class="checkbox">                    
                    @Html.CheckBox("IsAvailable", Model.IsAvailable)启用
                </label>
            </div>
        </div>
        <div class="form-actions">
            <button class="btn btn-primary" type="submit" data-loading-text="提交中" data-complete-text="完成"><i class="icon-ok icon-white"></i>保存</button>
            <button class="btn" type="button" onclick="history.go(-1);">返回</button>
        </div>
    </div>
}

L.S.Home/Areas/admin/Views/Info/Index.cshtml
@model PagedList.IPagedList<Info>

@{
    ViewBag.Title = "资讯列表";
}
<div>
    <ul class="breadcrumb admin-bread-ul">
        <li><a href="@Url.Action("Index","Info")">资讯</a> <span class="divider">/</span></li>
        <li class="active">资讯列表</li>
    </ul>
</div>
@foreach (SysRight r in ViewBag.pageTopRightList)
{
    if (r.ActionType == "View")
    {
        <a class="btn btn-primary" target="b" href="@r.MenuUrl" )>@r.DisplayName</a>
    }
    else
    {
        <a class="btn btn-primary ls-table-@r.ActionType.ToLower()" url="@r.MenuUrl" )>@r.DisplayName</a>
    }
}
@if (Model != null && Model.Count > 0)
{
    Html.RenderPartial("InfoList_Pa");
}
else { Html.RenderPartial("_NoData"); }

L.S.Home/Areas/admin/Views/Info/InfoList_Pa.cshtml
@model PagedList.IPagedList<Info>
@if (Model != null && Model.Count > 0)
{
    <div class=" ls-tablecontainer">
        <table class="table ls-table ls-table-hover-bright">
            <thead>
                <tr>
                    <th style="width:3%">
                        <input type="checkbox" class="ls-table-selectall" />
                    </th>
                    <th>
                        标题
                    </th>
                    <th>
                        添加人
                    </th>
                    <th>
                        添加日期
                    </th>
                    <th>
                        修改人
                    </th>
                    <th>
                        修改日期
                    </th>
                    <th>
                        启用
                    </th>
                    <th style="width:8%">操作</th>
                </tr>
            </thead>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        <input type="checkbox" class="ls-table-selecttr" value="@item.ID" />
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.AddByName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.AddDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UpdateByName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UpdateDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.IsAvailable)
                    </td>
                    <td>
                        <div class="btn-group">
                            @foreach (SysRight r in ViewBag.pageRightRightList)
                            {
                                if (r.ActionType == "View")
                                {
                                    <a class="btn btn-primary" target="_blank" href="@r.MenuUrl/@item.ID" )>@r.DisplayName</a>
                                }
                                else
                                {
                                    <a class="btn btn-primary ls-table-@r.ActionType.ToLower()" url="@r.MenuUrl/@item.ID" )>@r.DisplayName</a>
                                }
                            }
                        </div>
                    </td>
                </tr>
            }

        </table>
    </div>
    Html.RenderPartial("Pager_admin", Model);
}
else
{
    Html.RenderPartial("_NoData");
}