L.S.Home/Controllers/AsyncController.cs
using jsTree3.Models;
using L.S.Common;
using L.S.Interface;
using L.S.Interface.BLL;
using L.S.Model.DatabaseModel.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Web;
using System.Web.Mvc;

namespace L.S.Home.Controllers
{
    public class AsyncController : Controller
    {
        private IRightService rightService;
        private IDepService depService;
        private IUserBLL userBLL;
        private IRoleService roleService;
        private ICategoryService categoryService;

        public AsyncController(IRightService _rightService, IDepService _depService, IRoleService _roleService, IUserBLL _userBLL, ICategoryService _cateService)
        {
            rightService = _rightService;
            depService = _depService;
            userBLL = _userBLL;
            roleService = _roleService;
            categoryService = _cateService;
        }

        #region 异步请求方法

        #region 获取权限树
        /// <summary>
        /// 获取权限树
        /// </summary>
        /// <param name="selectNodeID"></param>
        /// <returns></returns>
        public ActionResult GetRightTree(string selectNodeID, string userid = "", string thisid = "", bool ismanage = false)
        {
            List<JsTree3Node> rightTreeNodes = new List<JsTree3Node>();
            var rightQueryable = rightService.GetQueryable(r => !r.IsDel);
            if (!ismanage)
            {
                rightQueryable = rightQueryable.Where(r => r.IsAvailable);
            }
            var rightList = rightQueryable.OrderBy(d => d.SortNo).ThenByDescending(d => d.AddDate).ToList();
            rightList.Where(r => r.ParentID == null).ToList().ForEach(r =>
            {
                bool disabled = r.RightIDPath.Trim('/').Split('/').Any(pid => pid == thisid);
                bool select = !string.IsNullOrEmpty(selectNodeID) && selectNodeID.Contains(r.ID);
                var node = new JsTree3Node
                {
                    id = r.ID,
                    text = r.Name,
                    state = new State(false, disabled, select),
                    children = new List<JsTree3Node>()
                };
                GenerateTree(node, rightList, selectNodeID, disabled, thisid);
                rightTreeNodes.Add(node);
            });

            return Json(rightTreeNodes, JsonRequestBehavior.AllowGet);
        }
        private void GenerateTree(JsTree3Node node, List<SysRight> list, string selectNodeID, bool parentDisabled, string thisid)
        {
            var childs = list.Where(d => d.ParentID == node.id).OrderBy(d => d.SortNo).ThenByDescending(d => d.AddDate).ToList();

            foreach (var c in childs)
            {
                bool disabled = parentDisabled || c.RightIDPath.Trim('/').Split('/').Any(pid => pid == thisid);
                bool select = !string.IsNullOrEmpty(selectNodeID) && selectNodeID.Contains(c.ID);
                var child = new JsTree3Node()
                {
                    id = c.ID,
                    text = c.Name,
                    state = new State(false, disabled, select),
                    children = new List<JsTree3Node>()
                };
                GenerateTree(child, list, selectNodeID, disabled, thisid);
                node.children.Add(child);
            }
        }
        #endregion

        #region 获取部门树
        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <param name="thisid">此ID对应的部门不包含在返回的树节点里（场景：部门编辑时可以选择上级部门，而这个选择范围不应该包含它自己）</param>
        /// <param name="selectNodeID">当前已选中的部门ID</param>
        /// <returns></returns>
        public ActionResult GetDepTree(string id = "root", string thisid = "", string selectNodeID = "")
        {
            id = string.IsNullOrEmpty(id) || id == "#" ? "root" : id;
            Expression<Func<SysDep, bool>> exp = d => d.DepFullIDPath.Contains(id);
            var deps = depService.GetList(exp).OrderBy(d => d.SortNo).ThenByDescending(d => d.AddDate).ToList();
            var level1 = deps.FirstOrDefault(d => d.ID == id);
            var level1_disabled = !string.IsNullOrEmpty(thisid) && level1.DepFullIDPath.Contains("/" + thisid +"/");
            bool select = selectNodeID == level1.ID;
            var root = new JsTree3Node()
            {
                id = level1.ID,
                text = level1.Name,
                state = new State(true, level1_disabled, select),
                children = new List<JsTree3Node>()
            };
            GenerateTree(root, deps, selectNodeID, level1_disabled, thisid);
            return Json(root, JsonRequestBehavior.AllowGet);
        }
        private void GenerateTree(JsTree3Node node, List<SysDep> list, string selectNodeID, bool parentDisabled, string thisid)
        {
            var childs = list.Where(d => d.ParentID == node.id).OrderBy(d => d.SortNo).ThenByDescending(d => d.AddDate).ToList();

            foreach (var c in childs)
            {
                var disabled = !string.IsNullOrEmpty(thisid) && (parentDisabled || c.DepFullIDPath.Contains("/" + thisid + "/"));
                bool select = selectNodeID == c.ID;
                var child = new JsTree3Node()
                {
                    id = c.ID,
                    text = c.Name,
                    state = new State(false, disabled, select),
                    children = new List<JsTree3Node>()
                };
                GenerateTree(child, list, selectNodeID, disabled, thisid);
                node.children.Add(child);
            }
        }
        #endregion

        #region 获取角色树
        public ActionResult GetRoleTree(string selectNodeID = "", string thisid = "", bool ismanage = false)
        {
            var cuser = userBLL.GetCurrentUser();
            //Expression<Func<SysRole, bool>> exp = sr => !sr.IsDel && sr.IsAvailable /*&& sr.RoleIDPath.Contains("/" + cuser.RoleID)*/;
            //var rightQueryable = rightService.GetQueryable(r => !r.IsDel);
            //if (!ismanage)
            //{
            //    rightQueryable = rightQueryable.Where(r => r.IsAvailable);
            //}
            var roleQueryable = roleService.GetQueryable(r => !r.IsDel);
            if (!ismanage)
            {
                roleQueryable = roleQueryable.Where(r => r.IsAvailable);
            }
            var roles = roleQueryable.OrderBy(d => d.SortNo).ThenByDescending(d => d.AddDate).ToList();
            var level1 = roles.FirstOrDefault(d => d.Parent == null);
            bool disabled = level1.RoleIDPath.Trim('/').Split('/').Any(rid => rid == thisid) || !cuser.RolesID.Contains(level1.ID);
            var selectedNodeIDs = selectNodeID.Split(',');
            bool selected = selectedNodeIDs.Any(nodeid => nodeid == level1.ID);
            var root = new JsTree3Node()
            {
                id = level1.ID,
                text = level1.Name,
                state = new State(true, disabled, selected),
                children = new List<JsTree3Node>()
            };
            GenerateRoleTree(root, roles, cuser.RolesID, disabled, selectedNodeIDs, thisid);
            return Json(root, JsonRequestBehavior.AllowGet);
        }
        private void GenerateRoleTree(JsTree3Node node, List<SysRole> list, string userRolesID, bool parentDisabled, string[] selectedNodeIDs, string thisid)
        {
            var childs = list.Where(d => d.ParentID == node.id).OrderBy(d => d.SortNo).ThenByDescending(d => d.AddDate).ToList();

            foreach (var c in childs)
            {
                bool disabled = c.RoleIDPath.Trim('/').Split('/').Any(rid => rid == thisid) || (parentDisabled && !userRolesID.Contains(c.ID));
                var child = new JsTree3Node()
                {
                    id = c.ID,
                    text = c.Name,
                    state = new State(false, disabled, selectedNodeIDs.Any(nodeid => nodeid == c.ID)),
                    children = new List<JsTree3Node>()
                };
                GenerateRoleTree(child, list, userRolesID, disabled, selectedNodeIDs, thisid);
                node.children.Add(child);
            }
        }
        #endregion

        #region 获取分类树
        public ActionResult GetCategoryTree(string selectNodeID = "", string thisid = "", bool ismanage = false, string cateTypeID = "")
        {
            List<JsTree3Node> root = new List<JsTree3Node>();
            var cuser = userBLL.GetCurrentUser();
            var categoryQueryable = categoryService.GetQueryable(r => !r.IsDel && r.CateTypeID == cateTypeID);
            if (!ismanage)
            {
                categoryQueryable = categoryQueryable.Where(r => r.IsAvailable);
            }
            var categorys = categoryQueryable.OrderBy(d => d.SortNo).ThenByDescending(d => d.AddDate).ToList();
            var level1 = categorys.Where(d => d.Parent == null).ToList();
            if (level1.Count>0)
            {
                level1.ForEach(c => 
                {
                    bool disabled = c.CategoryFullIDPath.Trim('/').Split('/').Any(rid => rid == thisid);
                    var selectedNodeIDs = selectNodeID.Split(',');
                    bool selected = selectedNodeIDs.Any(nodeid => nodeid == c.ID);
                    var node = new JsTree3Node()
                    {
                        id = c.ID,
                        text = c.Name,
                        state = new State(true, disabled, selected),
                        children = new List<JsTree3Node>()
                    };
                    GenerateCategoryTree(node, categorys, disabled, selectedNodeIDs, thisid);
                    root.Add(node);
                });
                
                return Json(root, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Content("未找到树的顶级节点");
            }
        }

L.S.Home/Areas/admin/Views/Category/CategoryList_Pa.cshtml
@model PagedList.IPagedList<Category>
@if (Model != null && Model.Count > 0)
{
    <div class=" ls-tablecontainer">
        <table class="table ls-table ls-table-hover-bright">
            <thead>
                <tr>
                    <th style="width:3%">
                        <input type="checkbox" class="ls-table-selectall" />
                    </th>
                    <th>
                        分类名称
                    </th>
                    <th>
                        添加人
                    </th>
                    <th>
                        添加日期
                    </th>
                    <th>
                        修改人
                    </th>
                    <th>
                        修改日期
                    </th>
                    <th>
                        启用
                    </th>
                    <th style="width:8%">操作</th>
                </tr>
            </thead>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        <input type="checkbox" class="ls-table-selecttr" value="@item.ID" />
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.AddByName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.AddDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UpdateByName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UpdateDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.IsAvailable)
                    </td>
                    <td>
                        <div class="btn-group">
                            @foreach (SysRight r in ViewBag.pageRightRightList)
                            {
                                if (r.ActionType == "View")
                                {
                                    <a class="btn btn-primary" href="@r.MenuUrl/@item.ID" )>@r.DisplayName</a>
                                }
                                else
                                {
                                    <a class="btn btn-primary ls-table-@r.ActionType.ToLower()" url="@r.MenuUrl/@item.ID" )>@r.DisplayName</a>
                                }
                            }
                        </div>
                    </td>
                </tr>
            }

        </table>
    </div>
    Html.RenderPartial("Pager_admin", Model);
}
else
{
    Html.RenderPartial("_NoData");
}

L.S.Home/Areas/admin/Views/Category/Create.cshtml
@model CategoryType
@{
    ViewBag.Title = "分类添加";
    CategoryType cateType= ViewBag.cateType as CategoryType;
}
<div>
    <ul class="breadcrumb admin-bread-ul">
        <li><a href="@Url.Action("Index","SysUser")">系统管理</a> <span class="divider">/</span></li>
        <li><a href="@Url.Action("Index","CategoryType")">分类管理</a> <span class="divider">/</span></li>
        <li class="active">分类添加</li>
    </ul>
</div>
@using (Ajax.BeginForm("Create", null, new AjaxOptions() { HttpMethod = "Post", OnBegin = "LS.admin.myfn.AjaxBegin('#form0')", OnSuccess = "LS.admin.myfn.AjaxSuccess" }, new { @class = "form-horizontal admin-form" }))
{
    @Html.AntiForgeryToken()
    <input type="hidden" value="@cateType.ID" name="CateTypeID" id="CateTypeID"/>
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="control-group">
            <label class="control-label">分类类型</label>
            <div class="controls">
                <input type="text" maxlength="16" placeholder="分类类型" validate min="2" max="10" readonly value="@cateType.Name">
                <span class="ls-msg help-inline"></span>
            </div>
        </div>
        <div class="control-group">
            <label for="Name" class="control-label">分类名称</label>
            <div class="controls">
                <input type="text" maxlength="16" name="Name" placeholder="名称" validate min="2" max="10">
                <span class="ls-msg help-inline"></span>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">上级分类</label>
            <div class="controls">
                <span class="treetext" id="ParentName"></span>
                <a class="btn" onclick="LS.admin.myfn.dialogeopendeptree({id:'ParentID',name:'ParentName'},'@Url.Action("GetCategoryTree", "Async", new { Area = ""})');">请选择</a>
                <a class="btn clearselectedtree" onclick="$(this).siblings('.treevalue').val(''); $(this).siblings('.treetext').text('');">清空</a>
                <input class="treevalue" type="hidden" name="ParentID" id="ParentID" validate min="2" max="36" msg="请选择上级分类" />
                <span class="ls-msg help-inline"></span>
            </div>
        </div>
        <div class="control-group">
            <div class="controls">
                <label class="checkbox">
                    <input type="checkbox" name="IsAvailable" value="true" checked="checked">启用
                </label>
            </div>
        </div>
        <div class="form-actions">
            <button class="btn btn-primary" type="submit" data-loading-text="提交中" data-complete-text="完成"><i class="icon-ok icon-white"></i>保存</button>
            <button class="btn" type="button" onclick="history.go(-1);">返回</button>
        </div>
    </div>
}

L.S.Home/Areas/admin/Views/Category/Edit.cshtml
@model CategoryViewModel
@{
    ViewBag.Title = "分类编辑";
    CategoryType cateType = ViewBag.cateType as CategoryType;
}
<div>
    <ul class="breadcrumb admin-bread-ul">
        <li><a href="@Url.Action("Index","SysUser")">系统管理</a> <span class="divider">/</span></li>
        <li><a href="@Url.Action("Index","CategoryType")">分类管理</a> <span class="divider">/</span></li>
        <li class="active">分类编辑</li>
    </ul>
</div>
@using (Ajax.BeginForm("Edit", null, new AjaxOptions() { HttpMethod = "Post", OnBegin = "LS.admin.myfn.AjaxBegin('#form0')", OnSuccess = "LS.admin.myfn.AjaxSuccess" }, new { @class = "form-horizontal admin-form" }))
{
    @Html.AntiForgeryToken()
    <input type="hidden" value="@Model.ID" name="ID" />
    <input type="hidden" value="@Model.AddBy" name="AddBy" />
    <input type="hidden" value="@Model.AddByName" name="AddByName" />
    <input type="hidden" value="@Model.AddDate" name="AddDate" />
    <input type="hidden" value="@cateType.ID" name="CateTypeID" id="CateTypeID" />

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="control-group">
            <label class="control-label">分类类型</label>
            <div class="controls">
                <input type="text" maxlength="16" placeholder="分类类型" validate min="2" max="10" readonly value="@cateType.Name">
                <span class="ls-msg help-inline"></span>
            </div>
        </div>
        <div class="control-group">
            <label for="Name" class="control-label">分类名称</label>
            <div class="controls">
                <input type="text" maxlength="16" name="Name" placeholder="名称" validate min="2" max="10" value="@Model.Name">
                <span class="ls-msg help-inline"></span>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">上级分类</label>
            <div class="controls">
                <span class="treetext" id="ParentName">@Model.ParentName</span>
                <a class="btn" onclick="LS.admin.myfn.dialogeopendeptree({id:'ParentID',name:'ParentName'},'@Url.Action("GetCategoryTree", "Async", new { Area = "", thisid = Model.ID })');">请选择</a>
                <a class="btn clearselectedtree" onclick="$(this).siblings('.treevalue').val(''); $(this).siblings('.treetext').text('');">清空</a>
                <input class="treevalue" type="hidden" name="ParentID" id="ParentID" value="@Model.ParentID" validate min="2" max="36" msg="请选择上级分类" />
                <span class="ls-msg help-inline"></span>
            </div>
        </div>
        <div class="control-group">
            <div class="controls">
                <label class="checkbox">
                    @Html.CheckBox("IsAvailable", Model.IsAvailable)启用
                </label>
            </div>
        </div>
        <div class="form-actions">
            <button class="btn btn-primary" type="submit" data-loading-text="提交中" data-complete-text="完成"><i class="icon-ok icon-white"></i>保存</button>
            <button class="btn" type="button" onclick="history.go(-1);">返回</button>
        </div>
    </div>
}

L.S.Home/Areas/admin/Views/Category/TreeIndex.cshtml
@{
    ViewBag.Title = "分类管理";
    string treeurl = Url.Action("GetCategoryTree", "Async", new { Area = "", ismanage = true ,cateTypeID= ViewBag.cateTypeID });
}
<style>
    .tree-area-container {
        border: 1px solid #852b99 !important;
        box-shadow: 0px 0px 4px #852b99;
        padding: 20px 0 20px 2% !important;
        margin-category: 2%;
        margin-top: 14px;
    }

        .tree-area-container:after {
            content: '\0020';
            display: block;
            clear: both;
        }

    .tree-area {
        width: 22%;
        padding: 10px;
        border: 1px solid lightgray;
    }

    .tree-category-form {
        margin-left: 2%;
        width: 72%;
    }

    form.admin-form {
        margin-left: 2%;
    }
        .tabbable{margin-top:14px;}
    .nav-tabs{margin-bottom:0px;margin-right:10px;}
    .tab-content{background:white;border:1px solid #ddd;border-top:none;padding:10px 10px;margin-right:10px;}
    .admin-nodata{margin: 14px 0 0 0;}
</style>
<div>
    <ul class="breadcrumb admin-bread-ul">
        <li><a href="@Url.Action("Index","SysUser")">系统管理</a> <span class="divider">/</span></li>
        <li class="active">分类管理</li>
    </ul>
</div>
@foreach (SysRight r in ViewBag.pageTopRightList)
{
    <a id="@r.ID" treetype="Category" class="btn btn-primary ls-treenode-@r.ActionType.ToLower()" url="@r.MenuUrl" )>@r.DisplayName</a>
}
<script>
    $(function () {
        function makeSelectedCategoryNodeToDetail() {
            var allselected = $("#CategoryTreeArea").jstree().get_selected(true);
            var categoryids = [];
            $(allselected).each(function (i) {
                categoryids.push(allselected[i].id);
            });
            if (categoryids != null && categoryids.length > 0) {
                $.ajax({
                    url: "GetCategory",
                    type: "get",
                    data: { id: categoryids.join(',') },
                    success: function (result) {
                        $("#ID").val(result.ID);
                        $("#Name").val(result.Name);
                        $("#ParentID").val(result.ParentID);
                        $("#ParentName").text(result.ParentName);
                        $("#AddBy").val(result.AddBy);
                        $("#AddDate").val(ConvertJSONDateToJSDateObject(result.AddDate));
                        //$("#CateTypeID").val(result.CateTypeID);
                        $("#SortNo").val(result.SortNo);
                        $("#CategoryEdit").attr("formaction", $("#CategoryEdit").attr('url'));
                        $("#IsAvailable-msg").addClass("alert");
                        if (result.IsAvailable) {
                            $("#IsAvailable-msg").removeClass("alert-error").addClass("alert-success").text("已启用");
                        } else {
                            $("#IsAvailable-msg").addClass("alert-error").removeClass("alert-success").text("未启用");
                        }
                    }
                });
            }
        }
        $("#CategoryTreeArea").jstree({
            "checkbox": {
                "keep_selected_style": true,
                "three_state": false,
            },
            "core": {
                "multiple": true,//不允许多选
                "themes": {
                    "stripes": true,//隔一行颜色不同
                },
                'data': {
                    'url': "/Async/GetCategoryTree?ismanage=true&cateTypeID=@ViewBag.cateTypeID",
                    'data': function (node) {
                        return { 'id': node.id, text: node.text };
                    }
                }
            },
            "plugins": ["search", "state","wholerow","checkbox"]
        }).on('click.jstree', makeSelectedCategoryNodeToDetail).on('state_ready.jstree', makeSelectedCategoryNodeToDetail);
        //$("#CategoryTreeArea").jstree().toggle_icons();

        var to = false;
        $('#CategorySearchBoxText').keyup(function () {
            if (to) { clearTimeout(to); }
            to = setTimeout(function () {
                var v = $('#CategorySearchBoxText').val();
                $('#CategoryTreeArea').jstree(true).search(v);
            }, 250);
        });
        //展开与折叠功能
        $("#toggle_all_syscategorytree").click(function () {
            var $this = $(this);
            var treestate = $this.attr("treestate");
            if (treestate == "close") {
                $("#CategoryTreeArea").jstree().open_all();
                $this.attr("treestate", "open");
                $this.val("折叠");
            }
            if (treestate == "open") {
                $("#CategoryTreeArea").jstree().close_all();
                $this.attr("treestate", "close");
                $this.val("展开");
            }
        });

        $("#toggle_select_all_syscategorytree").click(function () {
            var $this = $(this);
            var treestate = $this.attr("treestate");
            if (treestate == "unselected") {
                $("#CategoryTreeArea").jstree().select_all();
                $this.attr("treestate", "selected");
                $this.val("取消");
            }
            if (treestate == "selected") {
                $("#CategoryTreeArea").jstree().deselect_all();
                $this.attr("treestate", "unselected");
                $this.val("全选");
            }
        });

        $("#CategoryCreate").click(function (e) {
            var allselected = $("#CategoryTreeArea").jstree().get_selected(true);
            $("#ID").val("");
            $("#Name").val("");
            $("#AddBy").val("");
            $("#AddDate").val("");
            //$("#CateTypeID").val("");
            $("#SortNo").val("");
            $("#CategoryEdit").attr("formaction", $(this).attr("url"));
            $("#ParentID").val("");
            $("#ParentName").text("");
            $("#IsAvailable-msg").removeClass("alert").removeClass("alert-error").removeClass("alert-success").text("");
            if (allselected != null && allselected.length > 0) {
                var categoryids = allselected[0].id;
                var names = allselected[0].text;
                $("#ParentID").val(categoryids);
                $("#ParentName").text(names);                
            }
            $("#Name").focus();
        });
        $("#CategoryEdit").attr("formaction", $("#CategoryCreate").attr("url"));

        $("#Name").focus();
    });
</script>
<div class="tabbable">
    <ul class="nav nav-tabs">
        @foreach (CategoryType cateType in ViewBag.cateTypeList)
        {
            <li @if (ViewBag.cateTypeID == cateType.ID) { <text> class="active" </text> }><a href="@Url.Action("treeindex",new {cateTypeID=cateType.ID })" @*data-toggle="tab"使用这个表示tab切换之间都在本页面*@>@cateType.Name</a></li>
        }
    </ul>
    <div class="tab-content">
        <div class="tab-pane active">
            <div class="tree-area-container">
                <div class="tree-area fl">
                    <div class="" style="margin-bottom:10px;">
                        <div class="btn-group">
                            <input class="btn" type="button" id="toggle_all_syscategorytree" treestate="close" value="展开" />
                            <input class="btn" type="button" id="toggle_select_all_syscategorytree" treestate="unselected" value="全选" />
                        </div>
                    </div>
                    <input type="text" id="CategorySearchBoxText" value="" class="input" style="padding:4px; border-radius:4px; border:1px solid silver;">
                    <span class="selectedValue"></span>
                    <div id="CategoryTreeArea">
                    </div>
                </div>
                @model Category
                @using (Ajax.BeginForm("Create", null, new AjaxOptions() { HttpMethod = "Post", OnBegin = "LS.admin.myfn.AjaxBegin('#form0')", OnSuccess = "LS.admin.myfn.AjaxSuccess", OnFailure = "LS.admin.myfn.AjaxFailure" }, new { @class = "form-horizontal admin-form tree-category-form fl" }))
                {
                    @Html.AntiForgeryToken()
                    <input type="hidden" name="ID" id="ID" />
                    <input type="hidden" name="AddBy" id="AddBy" />
                    <input type="hidden" name="AddDate" id="AddDate" />
                    <input type="hidden" name="IsAvailable" id="IsAvailable" value="true" />
                    <input type="hidden" name="CateTypeID" id="CateTypeID" value="@ViewBag.cateTypeID"/>
                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="control-group">
                            <label for="Name" class="control-label">分类名称</label>
                            <div class="controls">
                                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @validate = "", @empty = "no" } })
                                <span class="ls-msg help-inline"></span>
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">上级分类</label>
                            <div class="controls">
                                <span class="treetext" id="ParentName"></span>
                                <a class="btn" url="@Url.Action("GetCategoryTree", "Async", new { Area = "" ,cateTypeID=ViewBag.cateTypeID})" 
                                   onclick="var url=$(this).attr('url')+'&thisid='+$('#ID').val();LS.admin.myfn.dialogeopencategorytree({id:'ParentID',name:'ParentName',toggledisplay:true,multiple:false},url);">请选择</a>
                                <a class="btn clearselectedtree" onclick="$(this).siblings('.treevalue').val(''); $(this).siblings('.treetext').text('');">清空</a>
                                <input class="treevalue" type="hidden" name="ParentID" id="ParentID" value="" />
                                <span class="ls-msg help-inline"></span>
                            </div>
                        </div>
                        <div class="control-group">
                            <label for="SortNo" class="control-label">排序号</label>
                            <div class="controls">
                                <input name="SortNo" id="SortNo" type="text" max="5" validate="number" empty="yes"/>
                                <span class="ls-msg help-inline"></span>
                            </div>
                        </div>
                        <div class="control-group">
                            <div class="controls">
                                <label class="checkbox" name="IsAvailable-msg" id="IsAvailable-msg">
                                </label>
                            </div>
                        </div>
                        <div class="form-actions">
                            @foreach (SysRight r in ViewBag.pageRightRightList)
                {
                                <button id="@r.ID" url="@r.MenuUrl.ToLower()" formaction="@r.MenuUrl.ToLower()" onclick="$('#form0').attr('action', $(this).attr('formaction'));" type="submit" class="btn btn-primary" data-loading-text="提交中" data-complete-text="完成">保存</button>
                            }
                            <button class="btn" type="button" onclick="history.go(-1);">返回</button>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>